// <auto-generated />
using System;
using API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(CurrencyContext))]
    partial class CurrencyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("API.CurrencyData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Base")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("CHF")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double>("EUR")
                        .HasColumnType("REAL");

                    b.Property<double>("GBP")
                        .HasColumnType("REAL");

                    b.Property<double>("JPY")
                        .HasColumnType("REAL");

                    b.Property<double>("PLN")
                        .HasColumnType("REAL");

                    b.Property<int>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Base = "USD",
                            CHF = 4.3231999999999999,
                            Date = new DateTime(2024, 3, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            EUR = 3.3300000000000001,
                            GBP = 2.2200000000000002,
                            JPY = 3.4220000000000002,
                            PLN = 5.3300000000000001,
                            Timestamp = 1238383463
                        },
                        new
                        {
                            Id = 2,
                            Base = "USD",
                            CHF = 3.4420000000000002,
                            Date = new DateTime(2024, 3, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            EUR = 2.3300000000000001,
                            GBP = 5.2199999999999998,
                            JPY = 6.4219999999999997,
                            PLN = 7.3300000000000001,
                            Timestamp = 1134438463
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
